[package]
name = "dotctl-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
clap.workspace = true
dialoguer.workspace = true
dirs.workspace = true
miette.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
which.workspace = true
tempfile.workspace = true

[dev-dependencies]
dotctl-testkit = { path = "../dotctl-testkit" }
